import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import AppBar from "@mui/material/AppBar";
import Typography from "@mui/material/Typography";
import Grid from "@mui/material/Grid";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Yuki&apos;s App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <AppBar position="static">
          <Grid container direction="row" justifyContent="center" alignItems="center">
            <Grid item xs={12} md={6}>
              <Typography variant="h6" component="div">
                Yuki&apos;s App
              </Typography>
            </Grid>
          </Grid>
        </AppBar>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
