import Head from 'next/head'

import Navigation from "../components/layout/navigation"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Yuki&apos;s App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />  
    
    </div>
  )
}
